version: '2'

services:
  app:
    image: ambientum/php:8.1-nginx
    container_name: app
    volumes:
      - ./src:/var/www/app
    ports:
      - "80:8080"
      - "443:8083"
    environment:
      - XDEBUG_ENABLED=true
      - PHP_IDE_CONFIG=serverName=ambientum
      - DOCKER_FOR_WINDOWS=${DOCKER_FOR_WINDOWS}
